defaults:
  - default.yaml

train_dataset:
  _target_: src.dataset.MTBench
  name: HuggingFaceH4/mt_bench_prompts
  prompt_template: llama2-base

val_dataset: ${.train_dataset}
test_dataset: ${.train_dataset}
