defaults:
  - default.yaml

train_dataset:
  _target_: src.dataset.PoseBench
  data_dir: ${data_dir}/posebench
  csv_filename: pose_80.csv
  prompt_template: vicuna-base
  samples: 80
  skip_header: false

val_dataset: ${.train_dataset}
test_dataset: ${.train_dataset}